# Generated by Django 5.0.1 on 2024-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User settings', 'verbose_name_plural': 'User settings'},
        ),
        migrations.AlterField(
            model_name='collecteditem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('NB', 'Non-Binary'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('No answer', 'Uninterested in answering this')], default='', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
