# Generated by Django 5.0.1 on 2024-01-31 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_treasure_iteminbox_userfriendz_delete_collecteditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminbox',
            options={'verbose_name': 'Inbox', 'verbose_name_plural': 'Inboxes'},
        ),
    ]
