# Generated by Django 5.0.1 on 2024-02-03 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_iteminbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox',
                'verbose_name_plural': 'Inboxes',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user', models.CharField(default='', max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('found_at_latitude', models.FloatField(default=0.0)),
                ('found_at_longitude', models.FloatField(default=0.0)),
                ('item_name', models.CharField(default='', max_length=255)),
                ('item_category', models.CharField(default='', max_length=255)),
                ('descriptor', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=600)),
                ('add_data', models.JSONField(default=dict)),
                ('pending', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owned_since', models.DateTimeField(blank=True, null=True)),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
