# Generated by Django 5.0.1 on 2024-02-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_iteminbox_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminbox',
            name='items',
            field=models.ManyToManyField(related_name='user_items', to='users.treasure'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='add_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='descriptor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
