# Generated by Django 5.0.1 on 2024-02-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_iteminbox_items_alter_treasure_add_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='add_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='descriptor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
