# Generated by Django 5.0.1 on 2024-02-04 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_message_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gift_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gift_requests', to=settings.AUTH_USER_MODEL)),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_gift', to='users.treasure')),
            ],
        ),
    ]
