# Generated by Django 5.0.1 on 2024-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_giftrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='miles_traveled_to_collect',
            field=models.FloatField(default=0.0),
        ),
    ]
