# Generated by Django 5.0.1 on 2024-02-05 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_treasure_descriptor_alter_uservisit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_latitude', models.FloatField(default=0.0)),
                ('location_longitude', models.FloatField(default=0.0)),
                ('visit_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
