# Generated by Django 5.0.1 on 2024-02-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_uservisitold_delete_uservisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVisitOld',
            new_name='UserVisit',
        ),
    ]
