# Generated by Django 5.0.1 on 2024-02-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_uservisitold_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
