# Generated by Django 5.0.1 on 2024-02-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0019_friendrequest_is_rejected_giftrequest_is_rejected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='InboxItem',
        ),
    ]
