# Generated by Django 5.0.1 on 2024-02-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_friendship_friendprofile_delete_userfriendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='owned_since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
