# Generated by Django 5.0.1 on 2024-02-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_treasure_owned_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='special_type',
            field=models.CharField(default='friend_request', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='giftrequest',
            name='special_type',
            field=models.CharField(default='gift_request', editable=False, max_length=50),
        ),
    ]
