# Generated by Django 5.0.1 on 2024-02-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_friendrequest_special_type_giftrequest_special_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasure',
            options={'ordering': ['-owned_since']},
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.message'),
        ),
    ]
