# Generated by Django 5.0.1 on 2024-02-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_treasure_options_remove_inboxitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='special_type',
            field=models.CharField(default='friend request', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='giftrequest',
            name='special_type',
            field=models.CharField(default='gift request', editable=False, max_length=50),
        ),
    ]
