# Generated by Django 5.0.1 on 2024-02-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_friendrequest_special_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendprofile',
            options={'ordering': ['-created_on'], 'verbose_name': 'User friendship', 'verbose_name_plural': 'User friendships'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='giftrequest',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='inboxitem',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'ordering': ['-visit_created_on']},
        ),
        migrations.RenameField(
            model_name='badrainbowzuser',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='friendprofile',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='giftrequest',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='inboxitem',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='uservisit',
            old_name='visit_datetime',
            new_name='visit_created_on',
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_item_for_message', to='users.message'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
