# Generated by Django 5.0.2 on 2025-01-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_friendprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='manual_dark_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
