# Generated by Django 5.0.2 on 2025-03-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_usersettings_expo_push_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
