# Generated by Django 5.0.2 on 2025-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_treasure_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='app_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
