# Generated by Django 5.0.2 on 2025-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_badrainbowzuser_app_setup_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='is_searchable_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
