# Generated by Django 5.0.2 on 2025-03-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
