# Generated by Django 5.0.2 on 2025-04-15 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_badrainbowzuser_is_subscribed_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='giver_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasures', to=settings.AUTH_USER_MODEL),
        ),
    ]
