# Generated by Django 5.0.2 on 2025-04-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_treasure_giver_name_alter_treasure_giver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_owners', models.PositiveIntegerField(default=1)),
                ('times_gifted', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('treasure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_history', to='users.treasure')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureOwnerChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasure_given_record', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasure_received_record', to=settings.AUTH_USER_MODEL)),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_owner_changes', to='users.treasure')),
                ('treasure_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_changes', to='users.treasurehistory')),
            ],
        ),
    ]
