# Generated by Django 5.0.2 on 2025-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_treasurehistory_treasureownerchangerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasureownerchangerecord',
            name='treasure_history',
        ),
        migrations.AlterModelOptions(
            name='treasureownerchangerecord',
            options={'verbose_name': 'Treasure Owner Change Record', 'verbose_name_plural': 'Treasure Owner Change Records'},
        ),
        migrations.AddField(
            model_name='treasure',
            name='times_gifted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treasure',
            name='total_unique_owners',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='TreasureHistory',
        ),
    ]
