# Generated by Django 5.0.2 on 2025-04-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_treasureownerchangerecord_treasure_history_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user'], name='users_inbox_user_id_a7a8f0_idx'),
        ),
    ]
