# Generated by Django 5.0.2 on 2025-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_inboxitem_users_inbox_user_id_a7a8f0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendprofile',
            index=models.Index(fields=['user'], name='users_frien_user_id_082a8e_idx'),
        ),
    ]
