# Generated by Django 5.0.2 on 2025-04-20 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_friendship_unique_friendship_initiator_reciprocator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSharedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User shared data',
                'verbose_name_plural': 'User shared data',
            },
        ),
    ]
