# Generated by Django 5.0.2 on 2025-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_usershareddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='location_city_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='treasure',
            name='location_country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
