# Generated by Django 5.0.2 on 2025-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_treasure_location_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='location_city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='location_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
