# Generated by Django 5.0.2 on 2025-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_treasure_location_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='location_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
