# Generated by Django 5.0.2 on 2025-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_treasure_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
