# Generated by Django 5.0.1 on 2024-01-24 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateTwinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Ruin', max_length=255)),
                ('direction_degree', models.FloatField(default=0.0)),
                ('direction', models.CharField(default='Unknown', max_length=255)),
                ('miles_away', models.FloatField(default=0.0)),
                ('location_id', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('tags', models.JSONField(default=dict)),
                ('wind_compass', models.CharField(default='', max_length=255)),
                ('wind_agreement_score', models.IntegerField(default=0)),
                ('street_view_image', models.URLField(blank=True, default='', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
