# Generated by Django 5.0.1 on 2024-01-28 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='wind_agreement_score',
            new_name='cloudiness',
        ),
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='location_id',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='wind_compass',
            new_name='stronger_wind_interaction',
        ),
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='direction_degree',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='miles_away',
            new_name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='climatetwinlocation',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='climatetwinlocation',
            name='street_view_image',
        ),
        migrations.RemoveField(
            model_name='climatetwinlocation',
            name='tags',
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='humidity_interaction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='pressure_interaction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='sunrise_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='sunset_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='wind_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='wind_friends',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='wind_speed_interaction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ClimateTwinDiscoveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Ruin', max_length=255)),
                ('direction_degree', models.FloatField(default=0.0)),
                ('direction', models.CharField(default='Unknown', max_length=255)),
                ('miles_away', models.FloatField(default=0.0)),
                ('location_id', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('tags', models.JSONField(default=dict)),
                ('wind_compass', models.CharField(default='', max_length=255)),
                ('wind_agreement_score', models.IntegerField(default=0)),
                ('street_view_image', models.URLField(blank=True, default='', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovery Location',
                'verbose_name_plural': 'Discovery Locations',
            },
        ),
    ]
