# Generated by Django 5.0.1 on 2024-01-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0003_climatetwindiscoverylocation_origin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwinlocation',
            name='special_harmony',
            field=models.BooleanField(default=False),
        ),
    ]
