# Generated by Django 5.0.1 on 2024-02-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0004_climatetwinlocation_special_harmony'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwindiscoverylocation',
            name='wind_harmony',
            field=models.BooleanField(default=False),
        ),
    ]
