# Generated by Django 5.0.1 on 2024-02-01 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0005_climatetwindiscoverylocation_wind_harmony'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateTwinExploreDiscoveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('explore_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwindiscoverylocation')),
                ('origin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwinlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explored Discovery Location',
                'verbose_name_plural': 'Explored Discovery Locations',
            },
        ),
    ]
