# Generated by Django 5.0.1 on 2024-02-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0006_climatetwinexplorediscoverylocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatetwinexplorediscoverylocation',
            name='origin_location',
        ),
    ]
