# Generated by Django 5.0.1 on 2024-02-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0007_remove_climatetwinexplorediscoverylocation_origin_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('temperature', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=255)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_direction', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('cloudiness', models.IntegerField(default=0)),
                ('sunrise_timestamp', models.BigIntegerField(default=0)),
                ('sunset_timestamp', models.BigIntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Location',
                'verbose_name_plural': 'Home Locations',
            },
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.homelocation'),
        ),
    ]
