# Generated by Django 5.0.1 on 2024-02-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0008_homelocation_climatetwinlocation_home_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatetwindiscoverylocation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Discovery Location', 'verbose_name_plural': 'Discovery Locations'},
        ),
        migrations.AlterModelOptions(
            name='climatetwinexplorediscoverylocation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Explored Discovery Location', 'verbose_name_plural': 'Explored Discovery Locations'},
        ),
        migrations.AlterModelOptions(
            name='climatetwinlocation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='homelocation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Home Location', 'verbose_name_plural': 'Home Locations'},
        ),
        migrations.RenameField(
            model_name='climatetwindiscoverylocation',
            old_name='creation_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='climatetwinexplorediscoverylocation',
            old_name='creation_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='climatetwinlocation',
            old_name='creation_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='homelocation',
            old_name='creation_date',
            new_name='created_on',
        ),
    ]
