# Generated by Django 5.0.2 on 2024-03-22 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0009_alter_climatetwindiscoverylocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatetwindiscoverylocation',
            options={'ordering': ['-id'], 'verbose_name': 'Discovery Location', 'verbose_name_plural': 'Discovery Locations'},
        ),
        migrations.CreateModel(
            name='ClimateTwinExploreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('explore_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwindiscoverylocation')),
                ('twin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwinlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explored Discovery Location',
                'verbose_name_plural': 'Explored Discovery Locations',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='ClimateTwinExploreDiscoveryLocation',
        ),
    ]
