# Generated by Django 4.2.10 on 2024-02-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0009_alter_climatetwindiscoverylocation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatetwindiscoverylocation',
            options={'ordering': ['-id'], 'verbose_name': 'Discovery Location', 'verbose_name_plural': 'Discovery Locations'},
        ),
    ]
