# Generated by Django 5.0.2 on 2024-03-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0010_alter_climatetwindiscoverylocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwinexplorediscoverylocation',
            name='twin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwinlocation'),
        ),
        migrations.AlterField(
            model_name='climatetwindiscoverylocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='climatetwinexplorediscoverylocation',
            name='explore_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwindiscoverylocation'),
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
