# Generated by Django 5.0.2 on 2024-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0010_alter_climatetwindiscoverylocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwindiscoverylocation',
            name='explore_type',
            field=models.CharField(default='discovery_location', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='explore_type',
            field=models.CharField(default='twin_location', editable=False, max_length=255),
        ),
    ]
