# Generated by Django 5.0.2 on 2025-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0011_climatetwindiscoverylocation_explore_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwinexplorelocation',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
