# Generated by Django 5.0.2 on 2025-02-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0013_currentlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentlocation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Current Location', 'verbose_name_plural': 'Current Locations'},
        ),
        migrations.AlterField(
            model_name='climatetwinexplorelocation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
