# Generated by Django 5.0.2 on 2025-02-14 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0014_alter_currentlocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='climatetwinlocation',
            index=models.Index(fields=['-created_on'], name='climatevisi_created_75d645_idx'),
        ),
    ]
