# Generated by Django 5.0.2 on 2025-02-14 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0015_climatetwinlocation_climatevisi_created_75d645_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='climatetwinexplorelocation',
            index=models.Index(fields=['-created_on'], name='climatevisi_created_212e42_idx'),
        ),
        migrations.AddIndex(
            model_name='climatetwinexplorelocation',
            index=models.Index(fields=['user', '-created_on'], name='climatevisi_user_id_5588b7_idx'),
        ),
    ]
