# Generated by Django 5.0.2 on 2025-03-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0017_climatetwindiscoverylocation_climatevisi_origin__a09b5c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateTwinSearchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_temperature', models.FloatField()),
                ('home_address', models.CharField(max_length=255)),
                ('climate_twin_temperature', models.FloatField()),
                ('climate_twin_address', models.CharField(max_length=255)),
                ('points_searched_on_land', models.IntegerField()),
                ('countries_searched', models.IntegerField()),
                ('total_points_generated', models.IntegerField()),
                ('openweathermap_calls', models.IntegerField()),
                ('google_map_calls', models.IntegerField()),
                ('high_variances', models.IntegerField()),
                ('preset_random_points_in_each_country', models.IntegerField()),
                ('preset_temp_diff_is_high_variance', models.BooleanField()),
                ('preset_num_high_variances_allowed', models.IntegerField()),
                ('preset_divider_for_point_gen_deviation', models.FloatField()),
                ('preset_num_final_candidates_required', models.IntegerField()),
                ('home_latitude', models.FloatField()),
                ('home_longitude', models.FloatField()),
                ('climate_twin_latitude', models.FloatField()),
                ('climate_twin_longitude', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('associated_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwinlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twin Search Stats',
                'verbose_name_plural': 'Twin Search Stats',
            },
        ),
    ]
