# Generated by Django 5.0.2 on 2025-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0018_climatetwinsearchstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatetwinsearchstats',
            name='preset_temp_diff_is_high_variance',
            field=models.IntegerField(),
        ),
    ]
