# Generated by Django 5.0.2 on 2025-03-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0019_alter_climatetwinsearchstats_preset_temp_diff_is_high_variance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatetwinsearchstats',
            options={'ordering': ['-id'], 'verbose_name': 'Twin Search Stats', 'verbose_name_plural': 'Twin Search Stats'},
        ),
    ]
