# Generated by Django 5.0.2 on 2025-04-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0020_alter_climatetwinsearchstats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlocation',
            name='explore_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwindiscoverylocation'),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='twin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwinlocation'),
        ),
    ]
