# Generated by Django 5.0.2 on 2025-04-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0021_alter_currentlocation_explore_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlocation',
            name='base_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_location_set', to='climatevisitor.climatetwinlocation'),
        ),
    ]
