# Generated by Django 5.0.2 on 2025-04-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0023_archiveddiscoverylocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTwinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('explore_type', models.CharField(default='twin_location', editable=False, max_length=255)),
                ('temperature', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=255)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_direction', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('cloudiness', models.IntegerField(default=0)),
                ('sunrise_timestamp', models.BigIntegerField(default=0)),
                ('sunset_timestamp', models.BigIntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('wind_friends', models.CharField(default='', max_length=255)),
                ('special_harmony', models.BooleanField(default=False)),
                ('details', models.TextField(default='')),
                ('experience', models.TextField(default='')),
                ('wind_speed_interaction', models.TextField(default='')),
                ('pressure_interaction', models.TextField(default='')),
                ('humidity_interaction', models.TextField(default='')),
                ('stronger_wind_interaction', models.CharField(default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('home_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.homelocation')),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatevisitor.climatetwinlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Location',
                'verbose_name_plural': 'Archived Locations',
                'ordering': ['-created_on'],
            },
        ),
    ]
