# Generated by Django 5.0.2 on 2025-04-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0024_archivedtwinlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedtwinlocation',
            name='original_location',
        ),
    ]
