# Generated by Django 5.0.2 on 2025-04-19 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0025_remove_archivedtwinlocation_original_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='climatetwinlocation',
            name='climatevisi_created_75d645_idx',
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='climatetwinlocation',
            index=models.Index(fields=['user'], name='climatevisi_user_id_af81fa_idx'),
        ),
    ]
