# Generated by Django 5.0.2 on 2025-04-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0026_remove_climatetwinlocation_climatevisi_created_75d645_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatetwinexplorelocation',
            name='explore_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwindiscoverylocation'),
        ),
        migrations.AlterField(
            model_name='climatetwinexplorelocation',
            name='twin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwinlocation'),
        ),
    ]
