# Generated by Django 5.0.2 on 2025-04-19 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0027_alter_climatetwinexplorelocation_explore_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveddiscoverylocation',
            name='origin_location',
        ),
        migrations.AlterField(
            model_name='climatetwindiscoverylocation',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.climatetwinlocation'),
        ),
    ]
