# Generated by Django 5.0.2 on 2025-04-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0028_remove_archiveddiscoverylocation_origin_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateTwinExploreLocation',
        ),
    ]
