# Generated by Django 5.0.2 on 2025-04-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0029_delete_climatetwinexplorelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtwinlocation',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.homelocation'),
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatevisitor.homelocation'),
        ),
    ]
