# Generated by Django 5.0.2 on 2025-04-20 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0030_alter_archivedtwinlocation_home_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='climatetwindiscoverylocation',
            name='climatevisi_origin__a09b5c_idx',
        ),
        migrations.AddIndex(
            model_name='climatetwindiscoverylocation',
            index=models.Index(fields=['user'], name='climatevisi_user_id_fd33be_idx'),
        ),
    ]
