# Generated by Django 5.0.2 on 2025-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0031_remove_climatetwindiscoverylocation_climatevisi_origin__a09b5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedtwinlocation',
            name='city_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='archivedtwinlocation',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='city_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
    ]
