# Generated by Django 5.0.2 on 2025-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0032_archivedtwinlocation_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelocation',
            name='city_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='homelocation',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
    ]
