# Generated by Django 5.0.2 on 2025-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0033_homelocation_city_name_homelocation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwindiscoverylocation',
            name='city_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='climatetwindiscoverylocation',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
    ]
