# Generated by Django 5.0.2 on 2025-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0034_climatetwindiscoverylocation_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatetwindiscoverylocation',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
    ]
