# Generated by Django 5.0.2 on 2025-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0035_climatetwindiscoverylocation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtwinlocation',
            name='city_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='archivedtwinlocation',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='climatetwindiscoverylocation',
            name='city_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='climatetwindiscoverylocation',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='climatetwindiscoverylocation',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='city_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='climatetwinlocation',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='city_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
