# Generated by Django 5.0.2 on 2025-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevisitor', '0036_alter_archivedtwinlocation_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedtwinlocation',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='climatetwinlocation',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homelocation',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
